### ISSUE TITLE
Infinite recursion on specific grammar rules

### ISSUE THREAD

**Issue by ElArtista** [orangeduck/mpc#32] opened 2015-06-14 14:55 UTC
First of, thanks for the amazing little library!
I have been working with a friend on a academic project, in which we had to implement a interpreter for a tiny given language. This language has to support compound array and list data types. This means we want to be able to define for example this kind of variables:

`list[int][] x`  (an array of integer lists)

The grammar that we defined at the start was this:
```
singletype   : "int" | "bool" | "char" ;
array        : <type> "[]"    ;
list         : "list" '[' <type> ']'   ;
type         : <singletype> | <list> | <array> ;
```

But mpc keeps falling in infinite loop and we have no idea why...
For know we removed the complex array support leaving it with only primitive types and N depth using this: 

```
singletype   : "int" | "bool" | "char" ;
array        : <singletype> ("[]")+    ;
list         : "list" '[' <type> ']'   ;
type         : <list> | <array> | <singletype> ;
```

Still we cannot find out if the problem appears to be in the library or in our grammar definition.
Any ideas are appreciated

**Comment by orangeduck** [comment] 2015-06-14 15:17
Hi ElArtista,

In all likeihood your grammar is left recursive, see:

https://github.com/orangeduck/mpc#the-parser-is-going-into-an-infinite-loop

I can't see right away what the problem might be with your specific grammar but perhaps reordering the options of `type` to put the base case (`singletype`) first will help.

- Dan

**Comment by ElArtista** [comment] 2015-06-14 15:19
Just tried it, still no luck.

**Comment by orangeduck** [comment] 2015-06-14 15:20
Can you post your grammar in full? It could be in another part.

**Comment by ElArtista** [comment] 2015-06-14 15:22
Here it is!

```
charsep      : "'" ;
strsep       : '"' ;

int          : /-?[0-9]+/ ;
char         : <charsep> (<specchar> | /[^']/) <charsep> ;
specchar     : /\\[ntr0']/ ;
string       : <strsep> /([\\]["]|[^"])*/ <strsep> ;
id           : /[a-zA-Z][a-zA-Z0-9_-?]*/ ;

mathoperator : ('+' | '-' | '*' | '/' | "mod") ;
booloperator : ('=' | "<>" | "<=" | ">=" | '<' | '>' | "and" | "or") ;

singletype   : "int" | "bool" | "char" ;
array        : <type> "[]"   ;
list         : "list" '[' <type> ']'   ;
type         : <singletype> | <list> | <array> ;

formal       : ("ref")? <type> <id> (',' <id>)* ;
header       : <type>? <id> '(' (<formal> (';' <formal>)*)? ')' ;

funcdef      : "def" <header> ':' (<funcdef> | <vardef> | <funcdecl>)* (<stmt> | <slcomment> | <mlcomment>)* "end" ;
funcdecl     : "decl" <header> ;
vardef       : <type> <id> (',' <id>)* ;

exprsimple   : <atom> | <int> | <char> | <string> | "false" | "true" | "nil" ;
expr         : "not" <expr> | "new" <type> '[' <expr> ']'
               | /nil\?/ '(' <expr> ')'
               | (<exprsimple> | '(' <expr> ')') (<mathoperator> <expr>)+
               | (<exprsimple> | '(' <expr> ')') <booloperator> <expr>
               | (<exprsimple> | '(' <expr> ')') '#' <expr>
               | ("head" | "tail") '(' <expr> ')' |  ('+' | '-') <expr>
               | <exprsimple> | '(' <expr> ')' | <id> ;

call         : <id> '(' (<expr> (',' <expr>)*)? ')' ;
atom         : <type> | (<call> | <id> | <string>) ('[' <expr> ']')+ | <call> | <id> | <string> ;
simple       : "skip" | <atom> ":=" <expr> | <call> ;
simplelist   : <simple> (',' <simple>)* ;

slcomment    : /%[^\r\n]*/ ;
mlcomment    : "<*" (<mlcomment> | /\*[^>]|[^*]/)* "*>" ;

stmt         : "return" <expr> | <simple> | "exit"
               | "if" <expr> ':' <stmt>+ ("elsif" <expr> ':' <stmt>+)* ("else" ':' <stmt>+)? "end"
               | "for" <simplelist> ';' <expr> ';' <simplelist> ':' <stmt>+ "end" ;

program      : /^/ <mlcomment>* <funcdef> <mlcomment>* /$/ ;
```

(Although as i said, i believe the problem occurs on these lines, because if i change the array definition in the workaround mentioned earlier everything works ok)

**Comment by ElArtista** [comment] 2015-06-14 15:27
Just confirmed my suspision, i stripped down all the grammar to this:

```
singletype   : "int" | "bool" | "char" ;
array        : <type> "[]"   ;
list         : "list" '[' <type> ']'   ;
type         : <singletype> | <list> | <array> ;

program      : <type>;
```

And still infinite recursion.

**Comment by orangeduck** [comment] 2015-06-14 15:34
Think I spotted it. The left recursion is between `array` and `type`:

```
array        : <type> "[]"    ;
list         : "list" '[' <type> ']'   ;
type         : <singletype> | <list> | <array> ;
```

If you are parsing an `array` then first you parse a `type`. If `type` fails to find a `singletype` or a `list` then again it will try to parse an `array` - which will kick off the process again. You need to factor this grammar somehow. Perhaps something like this:

```
list         : "list" '[' <type> ']'   ;
type         : (<singletype> | <list> | <array>) "[]"* ;
```

**Comment by ElArtista** [comment] 2015-06-14 15:50
Its an interesting workaround, but the problem is that like this an array definition is interpreted like a type and not like an array, and that is not gonna help me in semantic analysis..

**Comment by ElArtista** [comment] 2015-06-14 15:58
Is there any way in which we can see how it tries to parse the given input?

**Comment by orangeduck** [comment] 2015-06-14 16:08
Sorry there currently isn't a way to see how mpc tries to parse the input, but essentially it just applies the rules of the grammar that are given and when it gets to optional rules (`|`) it will just try to parse each rule in turn.

There are various ways you can factor the grammar but you'll have to find one that gives the labels you want and doesn't contain left recursion. Essentially the problem is that you have the `"[]"` on the right hand side in your language - which is not going to work if you want `array` to somehow be a subrule of `type`. In fact it should be more like the other way around if it is on the right. A `type` should optionally have a number of `"[]"` on the end - and a type without that should be some kind of `basictype` or something which is a subrule of the more general `type`.

But since this isn't a bug in the library I'm going to close the issue. I hope you manage to find a way to structure the grammar that works.

**Closed by orangeduck** 2015-06-14 16:08 UTC

**Comment by ElArtista** [comment] 2015-06-14 16:17
Thank you for your help.
