### ISSUE TITLE
problems with parsing

### ISSUE THREAD

**Issue by ikbenlike** [orangeduck/mpc#62] opened 2016-10-06 01:06 UTC
So, I'm trying to parse a file. However, I'm having some troubles with my grammar. This is my grammar:

```c
" ident     : /[a-zA-Z_][a-zA-Z0-9_]*/ ;                                                                    \n"
" number    : /-?[0-9]+(\\.[0-9]*)?/ ;                                                                      \n"
" character : /'.' | \".\"/ ;                                                                               \n"
" string    : /\"(\\\\.|[^\"])*\"/ ;                                                                        \n"
" boolean   : /true | false/ ;                                                                              \n"
"                                                                                                           \n"
" print     : /\"print\" (<ident> | <string>)/ ;                                                            \n"
" factor    : '(' <lexp> ')'                                                                                \n"
"           | <number>                                                                                      \n"
"           | <character>                                                                                   \n"
"           | <string>                                                                                      \n"
"           | <ident> '(' <lexp>? (',' <lexp>)* ')'                                                         \n"
"           | <ident> ;                                                                                     \n"
"                                                                                                           \n"
" term      : <factor> (('*' | '/' | '%') <factor>)* ;                                                      \n"
" lexp      : <term> <index>* (('+' | '-') <term> <index>* )* ;                                             \n"
"                                                                                                           \n"
" index     : '[' <number> ']' ;                                                                            \n"
" stmt      : '{' <stmt>* '}'                                                                               \n"
"           | \"while\" '(' <exp> <index>* ')' <stmt>                                                       \n"
"           | \"for\" '(' <exp> <index>* ')' <stmt>                                                         \n"
"           | \"if\"    '(' <exp> ')' <stmt>                                                                \n"
"           | \"loop\" <stmt>                                                                               \n"
"           | <ident> '=' <lexp> <index>* ';'                                                               \n"
"           | \"print\" '(' <lexp>? ')' ';'                                                                 \n"
"           | \"return\" <lexp>? ';'                                                                        \n"
"           | <ident> <index>* ';'                                                                          \n"
"           | <ident> '(' <ident>? (',' <ident>)* ')' <index>* ';';                                         \n"
"                                                                                                           \n"
" exp       : <lexp> '>' <lexp>                                                                             \n"
"           | <lexp> '<' <lexp>                                                                             \n"
"           | <lexp> \">=\" <lexp>                                                                          \n"
"           | <lexp> \"<=\" <lexp>                                                                          \n"
"           | <lexp> \"!=\" <lexp>                                                                          \n"
"           | <lexp> \"==\" <lexp>                                                                          \n"
"           | <lexp> \"in\" <lexp> ;                                                                        \n"
"                                                                                                           \n"
" typeident : (\"int\" | \"char\" | \"str\" | \"bool\" | \"float\" ) ;                              \n"
" procedure : (\"int\" | \"char\" | \"str\" | \"bool\" | \"float\" ) ':' <ident> '(' <args> ')' <body> ;    \n"
" decls     : <typeident> <ident> '=' ( <number> | <character> | <string> | <boolean> | <term> ) <index>* ';' ;  \n"
" args      : <typeident>? (',' <typeident>)* ;                                                             \n"
" body      : '{' <decls> <stmt>* '}' ;                                                                     \n"
" use       : (\"use\" /[a-zA-Z_\\/\\.][a-zA-Z0-9_\\/\\.]*/)* ;                                             \n"
" xenon     : /^/ <use> <decls> <procedure>* /$/ ;                                                          \n"
```

I'm trying to parse this file:
```
int:stuff(str string_to_print){
    int a = 1;
    float b = 1.1;
    str c = "stuff";
}
```
But, it's giving this error:
```
print.pxe:1:4: error: expected one of 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ_' at ':'
```

I have a version of the parser [here](https://github.com/ikbenlike/Xenon/blob/master/CXenon/src/parser.c) but that one has problems where it doesn't make a node the child of another node (while for everything else to work correctly, it should be).

**Comment by orangeduck** [comment] 2016-10-06 07:43
Looks like it is trying to parse the procedure as a `decls` and failing. I suspect this might work as intended if you change `<decls>` to `<decls>*`.

**Comment by ikbenlike** [comment] 2016-10-06 19:44
I assume you meant that about the `<decls>` on this line?
```c
" xenon     : /^/ <use> <decls>* <procedure>* /$/ ; \n"
```
Doing that (and a few other things) solved the problem, but it also created a new one. 
This is my full grammar: 
```c
" ident     : /[a-zA-Z_][a-zA-Z0-9_]*/ ;                                                                    \n"
" number    : /-?[0-9]+(\\.[0-9]*)?/ ;                                                                      \n"
" character : /'.' | \".\"/ ;                                                                               \n"
" string    : /\"(\\\\.|[^\"])*\"/ ;                                                                        \n"
" boolean   : /true | false/ ;                                                                              \n"
"                                                                                                           \n"
" print     : /\"print\" (<ident> | <string>)/ ;                                                            \n"
" factor    : '(' <lexp> ')'                                                                                \n"
"           | <number>                                                                                      \n"
"           | <character>                                                                                   \n"
"           | <string>                                                                                      \n"
"           | <ident> '(' <lexp>? (',' <lexp>)* ')'                                                         \n"
"           | <ident> ;                                                                                     \n"
"                                                                                                           \n"
" term      : <factor> (('*' | '/' | '%') <factor>)* ;                                                      \n"
" lexp      : <term> <index>* (('+' | '-') <term> <index>* )* ;                                             \n"
"                                                                                                           \n"
" index     : '[' <number> ']' ;                                                                            \n"
" stmt      : '{' <stmt>* '}'                                                                               \n"
"           | \"while\" '(' <exp> <index>* ')' <stmt>                                                       \n"
"           | \"for\" '(' <exp> <index>* ')' <stmt>                                                         \n"
"           | \"if\"    '(' <exp> ')' <stmt>                                                                \n"
"           | \"loop\" <stmt>                                                                               \n"
"           | <ident> '=' <lexp> <index>* ';'                                                               \n"
"           | \"print\" '(' <lexp>? ')' ';'                                                                 \n"
"           | \"return\" <lexp>? ';'                                                                        \n"
"           | <ident> <index>* ';'                                                                          \n"
"           | <ident> '(' <ident>? (',' <ident>)* ')' <index>* ';';                                         \n"
"                                                                                                           \n"
" exp       : <lexp> '>' <lexp>                                                                             \n"
"           | <lexp> '<' <lexp>                                                                             \n"
"           | <lexp> \">=\" <lexp>                                                                          \n"
"           | <lexp> \"<=\" <lexp>                                                                          \n"
"           | <lexp> \"!=\" <lexp>                                                                          \n"
"           | <lexp> \"==\" <lexp>                                                                          \n"
"           | <lexp> \"in\" <lexp> ;                                                                        \n"
"                                                                                                           \n"
" typeident : (\"int\" | \"char\" | \"str\" | \"bool\" | \"float\" ) <ident> ;                              \n"
" procedure : (\"int\" | \"char\" | \"str\" | \"bool\" | \"float\" ) ':' <ident> '(' <args> ')' <body> ;    \n"
" decls     : <typeident> '=' ( <number> | <character> | <string> | <boolean> | <term> ) <index>* ';' ;  \n"
" args      : <typeident>? (',' <typeident>)* ;                                                             \n"
" body      : '{' <decls> <stmt>* '}' ;                                                                     \n"
" use       : (\"use\" /[a-zA-Z_\\/\\.][a-zA-Z0-9_\\/\\.]*/)* ;                                             \n"
" `xenon     : /^/ <use> <decls>* <procedure>* /$/ ;`                                                          \n"
```
I'm trying to parse this file (yes, the variable names are just random crap):
```
int:stuff(str string_to_print){
    int alasfdk = 1;
    puts(stuff);
    float jKAHalskdjf = 1.1;
    str calskf = "stuff";
}
```
But, it's throwing this error:
```
print.pxe:4:11: error: expected '=', '[', ';' or '(' at 'j'
```

**Comment by orangeduck** [comment] 2016-10-06 21:42
Your grammar seems to say that inside the body of a function there should be a single variable declaration followed by multiple statements: `'{' <decls> <stmt>* '}'`. I think you probably mean something more like there should be multiple of either variable declarations or statements, something more like: `'{' (<decls> | <stmt>)* '}'`.

Anyway I think these are issues with your grammar rather than the behaviour of mpc which I think you can debug yourself. Feel free to reopen this issue if you think there is a bug with mpc but for now I am going to close it.

Hope you manage to get it working as intended :+1:

**Closed by orangeduck** 2016-10-06 21:42 UTC

**Comment by ikbenlike** [comment] 2016-10-07 05:25
That worked. Thanks for your help!
